### ISSUE TITLE
API can not get result

### ISSUE THREAD

**Issue by jtaxiexpress** [allanpereira99/tiktok_dl#1]
Hi , This is nice package . 
I did send request . 
I can not get result

but I did can get result yesterday

This is my code 
<img width="782" alt="スクリーンショット 2022-11-25 1 27 19" src="https://user-images.githubusercontent.com/86914073/203830930-1cc291ff-9793-4f09-871c-a6524f67d0a9.png">

and this is request on google .Is this correct ?
![スクリーンショット 2022-11-25 1 24 16](https://user-images.githubusercontent.com/86914073/203830944-a3b256a2-9a75-430e-b32b-3b72fab9b632.png)

**Comment by allanpereira99** [comment]
thanks for the report , api unfortunately changed but i fixed it now , use the new version

**Comment by allanpereira99** [comment]
check now please
